apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: asms-prod
data:
  asms-realm.json: |
    {
      "realm": "asms",
      "enabled": true,
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "roles": {
        "realm": [
          { "name": "ADMIN" },
          { "name": "RWA_MEMBER" },
          { "name": "OWNER" },
          { "name": "TENANT" },
          { "name": "VENDOR" },
          { "name": "SECURITY" },
          { "name": "SUPPORT_STAFF" }
        ]
      },
      "clients": [
        {
          "clientId": "asms-client",
          "enabled": true,
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "serviceAccountsEnabled": false,
          "protocol": "openid-connect"
        }
      ],
      "users": [
        {
          "username": "testuser",
          "enabled": true,
          "email": "testuser@asms.com",
          "firstName": "Test",
          "lastName": "User",
          "credentials": [
            {
              "type": "password",
              "value": "Test@1234",
              "temporary": false
            }
          ],
          "realmRoles": ["ADMIN"]
        },
        {
          "username": "rwa.member",
          "enabled": true,
          "email": "rwa@asms.com",
          "firstName": "RWA",
          "lastName": "Member",
          "credentials": [
            {
              "type": "password",
              "value": "Test@1234",
              "temporary": false
            }
          ],
          "realmRoles": ["RWA_MEMBER"]
        },
        {
          "username": "resident",
          "enabled": true,
          "email": "resident@asms.com",
          "firstName": "Resident",
          "lastName": "Owner",
          "credentials": [
            {
              "type": "password",
              "value": "Test@1234",
              "temporary": false
            }
          ],
          "realmRoles": ["OWNER"]
        },
        {
          "username": "security.guard",
          "enabled": true,
          "email": "security@asms.com",
          "firstName": "Security",
          "lastName": "Guard",
          "credentials": [
            {
              "type": "password",
              "value": "Test@1234",
              "temporary": false
            }
          ],
          "realmRoles": ["SECURITY"]
        }
      ]
    }
