apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asms-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/asms-gitops
    targetRevision: main
    path: helm/asms-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: asms-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
