apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: asms-prod
  labels:
    app: billing-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8087"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      initContainers:
        - name: wait-for-deps
          image: busybox:1.36
          securityContext:
            runAsUser: 10001
          command:
            - sh
            - -c
            - |
              until nc -z mongodb-0.mongodb 27017; do echo "waiting for mongodb"; sleep 3; done
              until nc -z kafka-0.kafka 9092; do echo "waiting for kafka"; sleep 3; done
      containers:
        - name: billing-service
          image: ${ECR_REGISTRY}/asms/billing-service:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: asms-common-config
            - secretRef:
                name: billing-service-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: asms-prod
spec:
  selector:
    app: billing-service
  ports:
    - port: 8087
      targetPort: 8087
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: billing-service-hpa
  namespace: asms-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: billing-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
