apiVersion: v1
kind: Secret
metadata:
  name: asms-secrets
  namespace: asms-prod
type: Opaque
stringData:
  MONGO_ROOT_PASSWORD: "asms-secret"
  MONGO_USERNAME: "asms"
  MONGO_PASSWORD: "asms-secret"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "Admin@asms#2024"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: asms-prod
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://asms:asms-secret@mongodb:27017/asms_user?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: support-service-secret
  namespace: asms-prod
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://asms:asms-secret@mongodb:27017/asms_support?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: amenity-service-secret
  namespace: asms-prod
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://asms:asms-secret@mongodb:27017/asms_amenity?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: visitor-service-secret
  namespace: asms-prod
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://asms:asms-secret@mongodb:27017/asms_visitor?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: asms-prod
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://asms:asms-secret@mongodb:27017/asms_payment?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secret
  namespace: asms-prod
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://asms:asms-secret@mongodb:27017/asms_billing?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-service-secret
  namespace: asms-prod
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://asms:asms-secret@mongodb:27017/asms_workflow?authSource=admin"
